### ISSUE TITLE
Needs rewrite or attribution

### ISSUE THREAD

**Issue by gj** [learn-co-curriculum/what-is-the-asset-pipeline#5]
The entire [Fingerprinting section](https://github.com/learn-co-curriculum/what-is-the-asset-pipeline/blob/master/README.md#fingerprinting), save the first two paragraphs, is 99% copied verbatim from the [Rails Guides primer on the Asset Pipeline](http://guides.rubyonrails.org/asset_pipeline.html#what-is-fingerprinting-and-why-should-i-care-questionmark). There are a few slight changes, such as this line in the Rails guide:

> Fingerprinting is a technique that makes the name of a file dependent on the contents of the file.

and its less-fortunate sibling in this README:

> Fingerprinting is a technique that makes the name of a filename dependent on the contents of the file.

**Comment by AnnJohn** [comment]
thank you for catching this. I attributed the information but will keep this issue open so that someone can hopefully update the language later. thanks again!

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#10.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
